name: "Report a Security Vulnerability"
description: "Report a security vulnerability to help us improve"
title: "Security: [Vulnerability Title]"
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        ### 🛑 Thank you for helping us stay secure!

        **Please do not report security vulnerabilities through public GitHub issues.**

        To ensure the confidentiality of the finding, please report security vulnerabilities privately. This gives us time to address the issue before it becomes public.

        ### **[Click here to report a security vulnerability privately](https://github.com/SaiSivarajuIN/ai_think/security/advisories/new)**

        We take all security reports seriously and will investigate them promptly. For more details, please see our [Security Policy](https://github.com/SaiSivarajuIN/ai_think/blob/main/SECURITY.md).

        Thank you for your responsible disclosure and for helping to keep our project and its users safe.

