name: "Bug Report"
description: "File a bug report to help us improve"
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - sivaraju
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a bug report. Please provide as much detail as possible to help us diagnose and fix the issue quickly.

  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of what the bug is. What did you observe? What did you expect?"
      placeholder: "When I do X, Y happens, but I expected Z."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to Reproduce"
      description: "Please provide a minimal, reproducible example. This is the most crucial part of any bug report."
      placeholder: |
        1. ...
        2. ...
        3. ...
        ```python
        # Minimal code to reproduce the bug
        ```
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Error Messages and Stack Trace"
      description: "If applicable, paste any relevant error messages or stack traces here. Please use code blocks for readability."
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: |
        Please provide details about your environment.
        - **OS:** [e.g., Ubuntu 22.04, Windows 11, macOS Ventura]
        - **Python Version:** [e.g., 3.10.8]
        - **Library Version:** [e.g., 1.2.3]
        - **Other relevant libraries and versions:**
      placeholder: |
        - OS:
        - Python Version:
        - Library Version:
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      description: "Please confirm the following before submitting."
      options:
        - label: "I have searched the existing issues and have not found a similar bug report."
          required: true
        - label: "I agree to follow this project's Code of Conduct."
          required: true

  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: "Is there anything else you'd like to add? Screenshots, related issues, etc."

