name: "Feature Request"
description: "Suggest an idea for this project"
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: "Thanks for suggesting a new feature! Please provide a clear description below."

  - type: textarea
    id: description
    attributes:
      label: "Feature Description"
      description: "A clear and concise description of the feature you'd like to see. What should it do? Why is it needed?"
      placeholder: "I would like a new feature that allows me to..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: "Add any other context, mockups, or screenshots about the feature request here."
