name: "User Story"
description: "Describe a user story for a new feature or improvement"
title: "[User Story]: "
labels: ["user-story", "enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a user story. Please follow the format below to help us understand the user's perspective and needs.

  - type: textarea
    id: user-story
    attributes:
      label: "User Story"
      description: "Describe the story from the user's perspective, following the format: 'As a [persona], I want to [action], so that [benefit].'"
      placeholder: "As a <persona>, I want to <action> so that I can <benefit>."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Provide a list of criteria that must be met for this story to be considered complete. Use a checklist format."
      placeholder: |
        - [ ] Given [context], when [action], then [outcome].
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Additional Context & Notes"
      description: "Add any other context, mockups, screenshots, or technical notes about the user story here."

  - type: input
    id: related-test-cases
    attributes:
      label: "Related Test Cases"
      description: "Link to any related test case issues (e.g., #456)."
      placeholder: "#456"
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      description: "Please confirm the following before submitting."
      options:
        - label: "I have searched the existing issues and have not found a similar user story."
          required: true
        - label: "This user story is well-defined and actionable."
          required: false
        - label: "I agree to follow this project's Code of Conduct."
          required: true
